#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\IndexController::index
cart: 
    path: /cart
    controller: App\Controller\CartController::index
app_add: 
    path: /add/{id}
    controller: App\Controller\CartController::add

cart_remove: 
    path: /remove/{id}
    controller: App\Controller\CartController::removeProduct

